### ISSUE TITLE
Reported as Malware on VirusTotal

### ISSUE THREAD

**Issue by Earth-And-Moon** [STaRDoGG/GeekDrop-Props#3]
I downloaded this program and submitted it in VirusTotal (just to make sure it's not a virus) and it tells me it's a virus.
https://www.virustotal.com/gui/file/8979524a5cf57e0bace3ad1ee2ab0e27fcaa39b123350f0df05123895c73cfc1

**Comment by jscottelblein** [comment]
@Earth-And-Moon Interesting. Not sure why it's flagged; though it seems like it's flagged mostly by engines I've never even heard of before.

When I get time maybe I'll try contacting them and asking what's up. It's clean though, the source code is all right here to look through.

Thanks for the heads up though.

**Comment by eggbean** [comment]
Windows Defender flagged it as high risk just now. I've had it on my system for months.

![image](https://github.com/STaRDoGG/GeekDrop-Props/assets/815311/f596bcfe-546b-470d-815c-91f35aa0d147)

**Comment by jscottelblein** [comment]
@eggbean Thanks for the heads-up.

Are you  using the pre-compiled one from geekdrop.com? Or did you download the source and compile it yourself?

It's been ages since I added the pre-compiled one to GD.com and after looking closer to the links above I see it mention it's packed with MPress ("Detected MPRESS obfuscator"), which is quite possible that I did that back then to help shrink the .exe down, but just don't recall offhand. I've always preferred to shrink my programs down; prob just an old habit going back to the old school days where drives were small and modems were 24.4K, lol.

.exe packers are notorious for sending malware scanners into a tailspin, even for totally clean software that they've packed.

I promise it's clean as a whistle, but if you still don't trust it, just grab and compile the source from here for peace of mind.

**Comment by eggbean** [comment]
I think I must have got it from the website. I tried replacing it with the binary in releases here on GitHub and Windows Defender immediately alerted again as soon as I downloaded the zip file.

**Comment by eggbean** [comment]
Even after Allowing the binary file in Windows Defender it keeps on coming up again when it does a periodic scan. Is there a build which I can use that doesn't have this problem?

**Comment by jscottelblein** [comment]
> Even after Allowing the binary file in Windows Defender it keeps on coming up again when it does a periodic scan. Is there a build which I can use that doesn't have this problem?

Odd.

Like I mentioned, you could just pull the repo and build the .exe yourself, assuming you have Visual Studio installed. If not, when I get a chance (not sure when; super busy) I can just do it for you and post a link here.

**Comment by eggbean** [comment]
That would be good if you could. I forked the repository and made [this GitHub Actions build file](https://github.com/eggbean/GeekDrop-Props/blob/master/.github/workflows/build.yml), but it fails on some sort of dependency problem. I am not familiar with compiling .net stuff, so I don't know what is needed.

https://github.com/eggbean/GeekDrop-Props/actions/runs/7078000271/job/19262998419

**Comment by eggbean** [comment]
I solved this problem by permanently adding the directory that contains the file to Defenders's exclusion list like this (PowerShell):

```PowerShell
Add-MpPreference -ExclusionPath "F:\Users\jason\winfiles\bin"
```
